#!/bin/sh

while read file
do
	case "$1" in
	"b") setbg "$file" & ;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"d")
		dmenu_promt "Really delete $file?" && rm "$file" && notify-send "$file deleted." ;;
	esac
done
