# /home/roman/.config/tmuxinator/dev.yml

name: dev
root: .

windows:
  - main:
      layout: a9e0,42x41,0,0[42x30,0,0{20x30,0,0,0,21x30,21,0,1},42x10,0,31{20x10,0,31,2,21x10,21,31,3}]
      panes:
        - ranger
        - make debug
        - amake
        - openocd 

