#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	r="$FILE" \
	f="fzf" \
	e="$EDITOR" \
	v="$EDITOR" \
	sv="sudo $EDITOR" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	blctl="bluetoothctl" \
	mon="tmuxinator" \
	tdev="tmuxinator start dev" \

# Just stuff
alias \
	amake="find -iregex '.*\.\(tex\|ms\|c\|h\)' | entr make"
	armp="openocd && amake"
	vc="v ~/.config/nvim/init.vim"
	ic="v ~/.config/i3/config"

